ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of sm'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_34 = ', GC_34
      WRITE(*,2) 'GC_35 = ', GC_35
      WRITE(*,2) 'GC_50 = ', GC_50
      WRITE(*,2) 'GC_53 = ', GC_53
      WRITE(*,2) 'GC_58 = ', GC_58
      WRITE(*,2) 'GC_69 = ', GC_69
      WRITE(*,2) 'GC_72 = ', GC_72
      WRITE(*,2) 'GC_81 = ', GC_81
      WRITE(*,2) 'GC_83 = ', GC_83
      WRITE(*,2) 'GC_100 = ', GC_100
