/********************************************************************
* Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDict();
extern void G__cpp_setup_inheritanceDict();
extern void G__cpp_setup_typetableDict();
extern void G__cpp_setup_memvarDict();
extern void G__cpp_setup_globalDict();
extern void G__cpp_setup_memfuncDict();
extern void G__cpp_setup_funcDict();
extern void G__set_cpp_environmentDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "WFGUI.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DictLN_TClass;
extern G__linked_taginfo G__DictLN_TBuffer;
extern G__linked_taginfo G__DictLN_TMemberInspector;
extern G__linked_taginfo G__DictLN_TObject;
extern G__linked_taginfo G__DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__DictLN_string;
extern G__linked_taginfo G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_TQObject;
extern G__linked_taginfo G__DictLN_TGWindow;
extern G__linked_taginfo G__DictLN_TGObject;
extern G__linked_taginfo G__DictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_TGFrame;
extern G__linked_taginfo G__DictLN_TGCompositeFrame;
extern G__linked_taginfo G__DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DictLN_TGTextButton;
extern G__linked_taginfo G__DictLN_TGVerticalFrame;
extern G__linked_taginfo G__DictLN_TGHorizontalFrame;
extern G__linked_taginfo G__DictLN_TGMainFrame;
extern G__linked_taginfo G__DictLN_TGGroupFrame;
extern G__linked_taginfo G__DictLN_TGTextEntry;
extern G__linked_taginfo G__DictLN_TGButtonGroup;
extern G__linked_taginfo G__DictLN_TGCheckButton;
extern G__linked_taginfo G__DictLN_TGRadioButton;
extern G__linked_taginfo G__DictLN_TGNumberEntry;
extern G__linked_taginfo G__DictLN_TCanvas;
extern G__linked_taginfo G__DictLN_TH1F;
extern G__linked_taginfo G__DictLN_TBox;
extern G__linked_taginfo G__DictLN_TThread;
extern G__linked_taginfo G__DictLN_TGLabel;
extern G__linked_taginfo G__DictLN_TGTab;
extern G__linked_taginfo G__DictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DictLN_TF1;
extern G__linked_taginfo G__DictLN_TLine;
extern G__linked_taginfo G__DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DictLN_TH2F;
extern G__linked_taginfo G__DictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_TGraph;
extern G__linked_taginfo G__DictLN_WFGUI;
extern G__linked_taginfo G__DictLN_Potentials;
extern G__linked_taginfo G__DictLN_Field;
extern G__linked_taginfo G__DictLN_Carriers;
extern G__linked_taginfo G__DictLN_TGHProgressBar;
extern G__linked_taginfo G__DictLN_TGComboBox;
extern G__linked_taginfo G__DictLN_TEllipse;
extern G__linked_taginfo G__DictLN_ParticleRadioButtonStatus_enum;

/* STUB derived class for protected member access */
