/********************************************************************
* /Users/nicolo/work/GruppoV_UFSD/Weightfield_evolution/weightfield2_Xcode/Weightfield.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /Users/nicolo/work/GruppoV_UFSD/Weightfield_evolution/weightfield2_Xcode/Weightfield.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableWeightfield();
extern void G__cpp_setup_inheritanceWeightfield();
extern void G__cpp_setup_typetableWeightfield();
extern void G__cpp_setup_memvarWeightfield();
extern void G__cpp_setup_globalWeightfield();
extern void G__cpp_setup_memfuncWeightfield();
extern void G__cpp_setup_funcWeightfield();
extern void G__set_cpp_environmentWeightfield();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Carriers.h"
#include "Field.h"
#include "Potentials.h"
#include "WFGUI.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__WeightfieldLN_TClass;
extern G__linked_taginfo G__WeightfieldLN_TBuffer;
extern G__linked_taginfo G__WeightfieldLN_TMemberInspector;
extern G__linked_taginfo G__WeightfieldLN_TObject;
extern G__linked_taginfo G__WeightfieldLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__WeightfieldLN_string;
extern G__linked_taginfo G__WeightfieldLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__WeightfieldLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WeightfieldLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__WeightfieldLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WeightfieldLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__WeightfieldLN_TCanvas;
extern G__linked_taginfo G__WeightfieldLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__WeightfieldLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__WeightfieldLN_TH1F;
extern G__linked_taginfo G__WeightfieldLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__WeightfieldLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__WeightfieldLN_TH2F;
extern G__linked_taginfo G__WeightfieldLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__WeightfieldLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WeightfieldLN_TQObject;
extern G__linked_taginfo G__WeightfieldLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__WeightfieldLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__WeightfieldLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WeightfieldLN_TThread;
extern G__linked_taginfo G__WeightfieldLN_TGObject;
extern G__linked_taginfo G__WeightfieldLN_TGWindow;
extern G__linked_taginfo G__WeightfieldLN_TGFrame;
extern G__linked_taginfo G__WeightfieldLN_TGCompositeFrame;
extern G__linked_taginfo G__WeightfieldLN_TGTextButton;
extern G__linked_taginfo G__WeightfieldLN_TGVerticalFrame;
extern G__linked_taginfo G__WeightfieldLN_TGHorizontalFrame;
extern G__linked_taginfo G__WeightfieldLN_TGMainFrame;
extern G__linked_taginfo G__WeightfieldLN_TGGroupFrame;
extern G__linked_taginfo G__WeightfieldLN_TGButtonGroup;
extern G__linked_taginfo G__WeightfieldLN_TGCheckButton;
extern G__linked_taginfo G__WeightfieldLN_TGRadioButton;
extern G__linked_taginfo G__WeightfieldLN_TGraph;
extern G__linked_taginfo G__WeightfieldLN_WFGUI;
extern G__linked_taginfo G__WeightfieldLN_Potentials;
extern G__linked_taginfo G__WeightfieldLN_Field;
extern G__linked_taginfo G__WeightfieldLN_Carriers;
extern G__linked_taginfo G__WeightfieldLN_TGTextEntry;
extern G__linked_taginfo G__WeightfieldLN_TGNumberEntry;
extern G__linked_taginfo G__WeightfieldLN_TGLabel;
extern G__linked_taginfo G__WeightfieldLN_TGTab;
extern G__linked_taginfo G__WeightfieldLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__WeightfieldLN_TLine;
extern G__linked_taginfo G__WeightfieldLN_TGHProgressBar;
extern G__linked_taginfo G__WeightfieldLN_TGComboBox;
extern G__linked_taginfo G__WeightfieldLN_TEllipse;
extern G__linked_taginfo G__WeightfieldLN_ParticleRadioButtonStatus_enum;

/* STUB derived class for protected member access */
